export const countries = [
	{
		currencyCode: 'SHP',
		currencyName: 'Saint Helenian Pound',
		currencySymbol: '£',
		countryCode: 'AC',
		countryName: 'Ascension Island',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'AD',
		countryName: 'Andorra',
	},
	{
		currencyCode: 'AED',
		currencyName: 'United Arab Emirates Dirham',
		currencySymbol: 'د.إ',
		countryCode: 'AE',
		countryName: 'United Arab Emirates',
	},
	{
		currencyCode: 'AFN',
		currencyName: 'Afghan Afghani',
		currencySymbol: '؋',
		countryCode: 'AF',
		countryName: 'Afghanistan',
	},
	{
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		currencySymbol: '$',
		countryCode: 'AG',
		countryName: 'Antigua & Barbuda',
	},
	{
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		currencySymbol: '$',
		countryCode: 'AI',
		countryName: 'Anguilla',
	},
	{
		currencyCode: 'ALL',
		currencyName: 'Albanian Lek',
		currencySymbol: 'L',
		countryCode: 'AL',
		countryName: 'Albania',
	},
	{
		currencyCode: 'AMD',
		currencyName: 'Armenian Dram',
		currencySymbol: 'դր.',
		countryCode: 'AM',
		countryName: 'Armenia',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'AO',
		countryName: 'Angola',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'AR',
		countryName: 'Argentina',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'AT',
		countryName: 'Austria',
	},
	{
		currencyCode: 'AUD',
		currencyName: 'Australian Dollar',
		currencySymbol: '$',
		countryCode: 'AU',
		countryName: 'Australia',
	},
	{
		currencyCode: 'AWG',
		currencyName: 'Aruban Florin',
		currencySymbol: 'ƒ',
		countryCode: 'AW',
		countryName: 'Aruba',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'AX',
		countryName: 'Åland Islands',
	},
	{
		currencyCode: 'AZN',
		currencyName: 'Azerbaijani Manat',
		currencySymbol: '₼',
		countryCode: 'AZ',
		countryName: 'Azerbaijan',
	},
	{
		currencyCode: 'BAM',
		currencyName: 'Bosnia and Herzegovina Convertible Mark',
		currencySymbol: 'КМ',
		countryCode: 'BA',
		countryName: 'Bosnia & Herzegovina',
	},
	{
		currencyCode: 'BBD',
		currencyName: 'Barbadian Dollar',
		currencySymbol: '$',
		countryCode: 'BB',
		countryName: 'Barbados',
	},
	{
		currencyCode: 'BDT',
		currencyName: 'Bangladeshi Taka',
		currencySymbol: '৳',
		countryCode: 'BD',
		countryName: 'Bangladesh',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'BE',
		countryName: 'Belgium',
	},
	{
		currencyCode: 'XOF',
		currencyName: 'West African Cfa Franc',
		currencySymbol: 'Fr',
		countryCode: 'BF',
		countryName: 'Burkina Faso',
	},
	{
		currencyCode: 'BGN',
		currencyName: 'Bulgarian Lev',
		currencySymbol: 'лв.',
		countryCode: 'BG',
		countryName: 'Bulgaria',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'BH',
		countryName: 'Bahrain',
	},
	{
		currencyCode: 'BIF',
		currencyName: 'Burundian Franc',
		currencySymbol: 'Fr',
		countryCode: 'BI',
		countryName: 'Burundi',
	},
	{
		currencyCode: 'XOF',
		currencyName: 'West African Cfa Franc',
		currencySymbol: 'Fr',
		countryCode: 'BJ',
		countryName: 'Benin',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'BL',
		countryName: 'St. Barthélemy',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'BM',
		countryName: 'Bermuda',
	},
	{
		currencyCode: 'BND',
		currencyName: 'Brunei Dollar',
		currencySymbol: '$',
		countryCode: 'BN',
		countryName: 'Brunei',
	},
	{
		currencyCode: 'BOB',
		currencyName: 'Bolivian Boliviano',
		currencySymbol: 'Bs.',
		countryCode: 'BO',
		countryName: 'Bolivia',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'BQ',
		countryName: 'Caribbean Netherlands',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'BR',
		countryName: 'Brazil',
	},
	{
		currencyCode: 'BSD',
		currencyName: 'Bahamian Dollar',
		currencySymbol: '$',
		countryCode: 'BS',
		countryName: 'Bahamas',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'BT',
		countryName: 'Bhutan',
	},
	{
		currencyCode: 'BWP',
		currencyName: 'Botswana Pula',
		currencySymbol: 'P',
		countryCode: 'BW',
		countryName: 'Botswana',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'BY',
		countryName: 'Belarus',
	},
	{
		currencyCode: 'BZD',
		currencyName: 'Belize Dollar',
		currencySymbol: '$',
		countryCode: 'BZ',
		countryName: 'Belize',
	},
	{
		currencyCode: 'CAD',
		currencyName: 'Canadian Dollar',
		currencySymbol: '$',
		countryCode: 'CA',
		countryName: 'Canada',
	},
	{
		currencyCode: 'AUD',
		currencyName: 'Australian Dollar',
		currencySymbol: '$',
		countryCode: 'CC',
		countryName: 'Cocos (Keeling) Islands',
	},
	{
		currencyCode: 'CDF',
		currencyName: 'Congolese Franc',
		currencySymbol: 'Fr',
		countryCode: 'CD',
		countryName: 'Congo - Kinshasa',
	},
	{
		currencyCode: 'XAF',
		currencyName: 'Central African Cfa Franc',
		currencySymbol: 'Fr',
		countryCode: 'CF',
		countryName: 'Central African Republic',
	},
	{
		currencyCode: 'XAF',
		currencyName: 'Central African Cfa Franc',
		currencySymbol: 'Fr',
		countryCode: 'CG',
		countryName: 'Congo - Brazzaville',
	},
	{
		currencyCode: 'CHF',
		currencyName: 'Swiss Franc',
		currencySymbol: 'CHF',
		countryCode: 'CH',
		countryName: 'Switzerland',
	},
	{
		currencyCode: 'XOF',
		currencyName: 'West African Cfa Franc',
		currencySymbol: 'Fr',
		countryCode: 'CI',
		countryName: 'Côte d’Ivoire',
	},
	{
		currencyCode: 'NZD',
		currencyName: 'New Zealand Dollar',
		currencySymbol: '$',
		countryCode: 'CK',
		countryName: 'Cook Islands',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'CL',
		countryName: 'Chile',
	},
	{
		currencyCode: 'XAF',
		currencyName: 'Central African Cfa Franc',
		currencySymbol: 'Fr',
		countryCode: 'CM',
		countryName: 'Cameroon',
	},
	{
		currencyCode: 'CNY',
		currencyName: 'Chinese Renminbi Yuan',
		currencySymbol: '¥',
		countryCode: 'CN',
		countryName: 'China',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'CO',
		countryName: 'Colombia',
	},
	{
		currencyCode: 'CRC',
		currencyName: 'Costa Rican Colón',
		currencySymbol: '₡',
		countryCode: 'CR',
		countryName: 'Costa Rica',
	},
	{
		currencyCode: 'CVE',
		currencyName: 'Cape Verdean Escudo',
		currencySymbol: '$',
		countryCode: 'CV',
		countryName: 'Cape Verde',
	},
	{
		currencyCode: 'ANG',
		currencyName: 'Netherlands Antillean Gulden',
		currencySymbol: 'ƒ',
		countryCode: 'CW',
		countryName: 'Curaçao',
	},
	{
		currencyCode: 'AUD',
		currencyName: 'Australian Dollar',
		currencySymbol: '$',
		countryCode: 'CX',
		countryName: 'Christmas Island',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'CY',
		countryName: 'Cyprus',
	},
	{
		currencyCode: 'CZK',
		currencyName: 'Czech Koruna',
		currencySymbol: 'Kč',
		countryCode: 'CZ',
		countryName: 'Czechia',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'DE',
		countryName: 'Germany',
	},
	{
		currencyCode: 'DJF',
		currencyName: 'Djiboutian Franc',
		currencySymbol: 'Fdj',
		countryCode: 'DJ',
		countryName: 'Djibouti',
	},
	{
		currencyCode: 'DKK',
		currencyName: 'Danish Krone',
		currencySymbol: 'kr.',
		countryCode: 'DK',
		countryName: 'Denmark',
	},
	{
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		currencySymbol: '$',
		countryCode: 'DM',
		countryName: 'Dominica',
	},
	{
		currencyCode: 'DOP',
		currencyName: 'Dominican Peso',
		currencySymbol: '$',
		countryCode: 'DO',
		countryName: 'Dominican Republic',
	},
	{
		currencyCode: 'DZD',
		currencyName: 'Algerian Dinar',
		currencySymbol: 'د.ج',
		countryCode: 'DZ',
		countryName: 'Algeria',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'EC',
		countryName: 'Ecuador',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'EE',
		countryName: 'Estonia',
	},
	{
		currencyCode: 'EGP',
		currencyName: 'Egyptian Pound',
		currencySymbol: 'ج.م',
		countryCode: 'EG',
		countryName: 'Egypt',
	},
	{
		currencyCode: 'MAD',
		currencyName: 'Moroccan Dirham',
		currencySymbol: 'د.م.',
		countryCode: 'EH',
		countryName: 'Western Sahara',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'ER',
		countryName: 'Eritrea',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'ES',
		countryName: 'Spain',
	},
	{
		currencyCode: 'ETB',
		currencyName: 'Ethiopian Birr',
		currencySymbol: 'Br',
		countryCode: 'ET',
		countryName: 'Ethiopia',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'FI',
		countryName: 'Finland',
	},
	{
		currencyCode: 'FJD',
		currencyName: 'Fijian Dollar',
		currencySymbol: '$',
		countryCode: 'FJ',
		countryName: 'Fiji',
	},
	{
		currencyCode: 'FKP',
		currencyName: 'Falkland Pound',
		currencySymbol: '£',
		countryCode: 'FK',
		countryName: 'Falkland Islands',
	},
	{
		currencyCode: 'DKK',
		currencyName: 'Danish Krone',
		currencySymbol: 'kr.',
		countryCode: 'FO',
		countryName: 'Faroe Islands',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'FR',
		countryName: 'France',
	},
	{
		currencyCode: 'XOF',
		currencyName: 'West African Cfa Franc',
		currencySymbol: 'Fr',
		countryCode: 'GA',
		countryName: 'Gabon',
	},
	{
		currencyCode: 'GBP',
		currencyName: 'British Pound',
		currencySymbol: '£',
		countryCode: 'GB',
		countryName: 'United Kingdom',
	},
	{
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		currencySymbol: '$',
		countryCode: 'GD',
		countryName: 'Grenada',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'GE',
		countryName: 'Georgia',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'GF',
		countryName: 'French Guiana',
	},
	{
		currencyCode: 'GBP',
		currencyName: 'British Pound',
		currencySymbol: '£',
		countryCode: 'GG',
		countryName: 'Guernsey',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'GH',
		countryName: 'Ghana',
	},
	{
		currencyCode: 'GBP',
		currencyName: 'British Pound',
		currencySymbol: '£',
		countryCode: 'GI',
		countryName: 'Gibraltar',
	},
	{
		currencyCode: 'DKK',
		currencyName: 'Danish Krone',
		currencySymbol: 'kr.',
		countryCode: 'GL',
		countryName: 'Greenland',
	},
	{
		currencyCode: 'GMD',
		currencyName: 'Gambian Dalasi',
		currencySymbol: 'D',
		countryCode: 'GM',
		countryName: 'Gambia',
	},
	{
		currencyCode: 'GNF',
		currencyName: 'Guinean Franc',
		currencySymbol: 'Fr',
		countryCode: 'GN',
		countryName: 'Guinea',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'GP',
		countryName: 'Guadeloupe',
	},
	{
		currencyCode: 'XAF',
		currencyName: 'Central African Cfa Franc',
		currencySymbol: 'Fr',
		countryCode: 'GQ',
		countryName: 'Equatorial Guinea',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'GR',
		countryName: 'Greece',
	},
	{
		currencyCode: 'GBP',
		currencyName: 'British Pound',
		currencySymbol: '£',
		countryCode: 'GS',
		countryName: 'South Georgia & South Sandwich Islands',
	},
	{
		currencyCode: 'GTQ',
		currencyName: 'Guatemalan Quetzal',
		currencySymbol: 'Q',
		countryCode: 'GT',
		countryName: 'Guatemala',
	},
	{
		currencyCode: 'XOF',
		currencyName: 'West African Cfa Franc',
		currencySymbol: 'Fr',
		countryCode: 'GW',
		countryName: 'Guinea-Bissau',
	},
	{
		currencyCode: 'GYD',
		currencyName: 'Guyanese Dollar',
		currencySymbol: '$',
		countryCode: 'GY',
		countryName: 'Guyana',
	},
	{
		currencyCode: 'HKD',
		currencyName: 'Hong Kong Dollar',
		currencySymbol: '$',
		countryCode: 'HK',
		countryName: 'Hong Kong SAR',
	},
	{
		currencyCode: 'HNL',
		currencyName: 'Honduran Lempira',
		currencySymbol: 'L',
		countryCode: 'HN',
		countryName: 'Honduras',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'HR',
		countryName: 'Croatia',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'HT',
		countryName: 'Haiti',
	},
	{
		currencyCode: 'HUF',
		currencyName: 'Hungarian Forint',
		currencySymbol: 'Ft',
		countryCode: 'HU',
		countryName: 'Hungary',
	},
	{
		currencyCode: 'IDR',
		currencyName: 'Indonesian Rupiah',
		currencySymbol: 'Rp',
		countryCode: 'ID',
		countryName: 'Indonesia',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'IE',
		countryName: 'Ireland',
	},
	{
		currencyCode: 'GBP',
		currencyName: 'British Pound',
		currencySymbol: '£',
		countryCode: 'IM',
		countryName: 'Isle of Man',
	},
	{
		currencyCode: 'INR',
		currencyName: 'Indian Rupee',
		currencySymbol: '₹',
		countryCode: 'IN',
		countryName: 'India',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'IO',
		countryName: 'British Indian Ocean Territory',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'IQ',
		countryName: 'Iraq',
	},
	{
		currencyCode: 'ISK',
		currencyName: 'Icelandic Króna',
		currencySymbol: 'kr',
		countryCode: 'IS',
		countryName: 'Iceland',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'IT',
		countryName: 'Italy',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'JE',
		countryName: 'Jersey',
	},
	{
		currencyCode: 'JMD',
		currencyName: 'Jamaican Dollar',
		currencySymbol: '$',
		countryCode: 'JM',
		countryName: 'Jamaica',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'JO',
		countryName: 'Jordan',
	},
	{
		currencyCode: 'JPY',
		currencyName: 'Japanese Yen',
		currencySymbol: '¥',
		countryCode: 'JP',
		countryName: 'Japan',
	},
	{
		currencyCode: 'KES',
		currencyName: 'Kenyan Shilling',
		currencySymbol: 'KSh',
		countryCode: 'KE',
		countryName: 'Kenya',
	},
	{
		currencyCode: 'KGS',
		currencyName: 'Kyrgyzstani Som',
		currencySymbol: 'som',
		countryCode: 'KG',
		countryName: 'Kyrgyzstan',
	},
	{
		currencyCode: 'KHR',
		currencyName: 'Cambodian Riel',
		currencySymbol: '៛',
		countryCode: 'KH',
		countryName: 'Cambodia',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'KI',
		countryName: 'Kiribati',
	},
	{
		currencyCode: 'KMF',
		currencyName: 'Comorian Franc',
		currencySymbol: 'Fr',
		countryCode: 'KM',
		countryName: 'Comoros',
	},
	{
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		currencySymbol: '$',
		countryCode: 'KN',
		countryName: 'St. Kitts & Nevis',
	},
	{
		currencyCode: 'KRW',
		currencyName: 'South Korean Won',
		currencySymbol: '₩',
		countryCode: 'KR',
		countryName: 'South Korea',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'KW',
		countryName: 'Kuwait',
	},
	{
		currencyCode: 'KYD',
		currencyName: 'Cayman Islands Dollar',
		currencySymbol: '$',
		countryCode: 'KY',
		countryName: 'Cayman Islands',
	},
	{
		currencyCode: 'KZT',
		currencyName: 'Kazakhstani Tenge',
		currencySymbol: '〒',
		countryCode: 'KZ',
		countryName: 'Kazakhstan',
	},
	{
		currencyCode: 'LAK',
		currencyName: 'Lao Kip',
		currencySymbol: '₭',
		countryCode: 'LA',
		countryName: 'Laos',
	},
	{
		currencyCode: 'LBP',
		currencyName: 'Lebanese Pound',
		currencySymbol: 'ل.ل',
		countryCode: 'LB',
		countryName: 'Lebanon',
	},
	{
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		currencySymbol: '$',
		countryCode: 'LC',
		countryName: 'St. Lucia',
	},
	{
		currencyCode: 'CHF',
		currencyName: 'Swiss Franc',
		currencySymbol: 'CHF',
		countryCode: 'LI',
		countryName: 'Liechtenstein',
	},
	{
		currencyCode: 'LKR',
		currencyName: 'Sri Lankan Rupee',
		currencySymbol: '₨',
		countryCode: 'LK',
		countryName: 'Sri Lanka',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'LR',
		countryName: 'Liberia',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'LS',
		countryName: 'Lesotho',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'LT',
		countryName: 'Lithuania',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'LU',
		countryName: 'Luxembourg',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'LV',
		countryName: 'Latvia',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'LY',
		countryName: 'Libya',
	},
	{
		currencyCode: 'MAD',
		currencyName: 'Moroccan Dirham',
		currencySymbol: 'د.م.',
		countryCode: 'MA',
		countryName: 'Morocco',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'MC',
		countryName: 'Monaco',
	},
	{
		currencyCode: 'MDL',
		currencyName: 'Moldovan Leu',
		currencySymbol: 'L',
		countryCode: 'MD',
		countryName: 'Moldova',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'ME',
		countryName: 'Montenegro',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'MF',
		countryName: 'St. Martin',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'MG',
		countryName: 'Madagascar',
	},
	{
		currencyCode: 'MKD',
		currencyName: 'Macedonian Denar',
		currencySymbol: 'ден',
		countryCode: 'MK',
		countryName: 'North Macedonia',
	},
	{
		currencyCode: 'XOF',
		currencyName: 'West African Cfa Franc',
		currencySymbol: 'Fr',
		countryCode: 'ML',
		countryName: 'Mali',
	},
	{
		currencyCode: 'MMK',
		currencyName: 'Myanmar Kyat',
		currencySymbol: 'K',
		countryCode: 'MM',
		countryName: 'Myanmar (Burma)',
	},
	{
		currencyCode: 'MNT',
		currencyName: 'Mongolian Tögrög',
		currencySymbol: '₮',
		countryCode: 'MN',
		countryName: 'Mongolia',
	},
	{
		currencyCode: 'MOP',
		currencyName: 'Macanese Pataca',
		currencySymbol: 'P',
		countryCode: 'MO',
		countryName: 'Macao SAR',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'MQ',
		countryName: 'Martinique',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'MR',
		countryName: 'Mauritania',
	},
	{
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		currencySymbol: '$',
		countryCode: 'MS',
		countryName: 'Montserrat',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'MT',
		countryName: 'Malta',
	},
	{
		currencyCode: 'MUR',
		currencyName: 'Mauritian Rupee',
		currencySymbol: '₨',
		countryCode: 'MU',
		countryName: 'Mauritius',
	},
	{
		currencyCode: 'MVR',
		currencyName: 'Maldivian Rufiyaa',
		currencySymbol: 'MVR',
		countryCode: 'MV',
		countryName: 'Maldives',
	},
	{
		currencyCode: 'MWK',
		currencyName: 'Malawian Kwacha',
		currencySymbol: 'MK',
		countryCode: 'MW',
		countryName: 'Malawi',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'MX',
		countryName: 'Mexico',
	},
	{
		currencyCode: 'MYR',
		currencyName: 'Malaysian Ringgit',
		currencySymbol: 'RM',
		countryCode: 'MY',
		countryName: 'Malaysia',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'MZ',
		countryName: 'Mozambique',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'NA',
		countryName: 'Namibia',
	},
	{
		currencyCode: 'XPF',
		currencyName: 'Cfp Franc',
		currencySymbol: 'Fr',
		countryCode: 'NC',
		countryName: 'New Caledonia',
	},
	{
		currencyCode: 'XOF',
		currencyName: 'West African Cfa Franc',
		currencySymbol: 'Fr',
		countryCode: 'NE',
		countryName: 'Niger',
	},
	{
		currencyCode: 'AUD',
		currencyName: 'Australian Dollar',
		currencySymbol: '$',
		countryCode: 'NF',
		countryName: 'Norfolk Island',
	},
	{
		currencyCode: 'NGN',
		currencyName: 'Nigerian Naira',
		currencySymbol: '₦',
		countryCode: 'NG',
		countryName: 'Nigeria',
	},
	{
		currencyCode: 'NIO',
		currencyName: 'Nicaraguan Córdoba',
		currencySymbol: 'C$',
		countryCode: 'NI',
		countryName: 'Nicaragua',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'NL',
		countryName: 'Netherlands',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'NO',
		countryName: 'Norway',
	},
	{
		currencyCode: 'NPR',
		currencyName: 'Nepalese Rupee',
		currencySymbol: '₨',
		countryCode: 'NP',
		countryName: 'Nepal',
	},
	{
		currencyCode: 'AUD',
		currencyName: 'Australian Dollar',
		currencySymbol: '$',
		countryCode: 'NR',
		countryName: 'Nauru',
	},
	{
		currencyCode: 'NZD',
		currencyName: 'New Zealand Dollar',
		currencySymbol: '$',
		countryCode: 'NU',
		countryName: 'Niue',
	},
	{
		currencyCode: 'NZD',
		currencyName: 'New Zealand Dollar',
		currencySymbol: '$',
		countryCode: 'NZ',
		countryName: 'New Zealand',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'OM',
		countryName: 'Oman',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'PA',
		countryName: 'Panama',
	},
	{
		currencyCode: 'PEN',
		currencyName: 'Peruvian Sol',
		currencySymbol: 'S/.',
		countryCode: 'PE',
		countryName: 'Peru',
	},
	{
		currencyCode: 'XPF',
		currencyName: 'Cfp Franc',
		currencySymbol: 'Fr',
		countryCode: 'PF',
		countryName: 'French Polynesia',
	},
	{
		currencyCode: 'PGK',
		currencyName: 'Papua New Guinean Kina',
		currencySymbol: 'K',
		countryCode: 'PG',
		countryName: 'Papua New Guinea',
	},
	{
		currencyCode: 'PHP',
		currencyName: 'Philippine Peso',
		currencySymbol: '₱',
		countryCode: 'PH',
		countryName: 'Philippines',
	},
	{
		currencyCode: 'PKR',
		currencyName: 'Pakistani Rupee',
		currencySymbol: '₨',
		countryCode: 'PK',
		countryName: 'Pakistan',
	},
	{
		currencyCode: 'PLN',
		currencyName: 'Polish Złoty',
		currencySymbol: 'zł',
		countryCode: 'PL',
		countryName: 'Poland',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'PM',
		countryName: 'St. Pierre & Miquelon',
	},
	{
		currencyCode: 'NZD',
		currencyName: 'New Zealand Dollar',
		currencySymbol: '$',
		countryCode: 'PN',
		countryName: 'Pitcairn Islands',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'PT',
		countryName: 'Portugal',
	},
	{
		currencyCode: 'PYG',
		currencyName: 'Paraguayan Guaraní',
		currencySymbol: '₲',
		countryCode: 'PY',
		countryName: 'Paraguay',
	},
	{
		currencyCode: 'QAR',
		currencyName: 'Qatari Riyal',
		currencySymbol: 'ر.ق',
		countryCode: 'QA',
		countryName: 'Qatar',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'RE',
		countryName: 'Réunion',
	},
	{
		currencyCode: 'RON',
		currencyName: 'Romanian Leu',
		currencySymbol: 'Lei',
		countryCode: 'RO',
		countryName: 'Romania',
	},
	{
		currencyCode: 'RSD',
		currencyName: 'Serbian Dinar',
		currencySymbol: 'РСД',
		countryCode: 'RS',
		countryName: 'Serbia',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'RU',
		countryName: 'Russia',
	},
	{
		currencyCode: 'RWF',
		currencyName: 'Rwandan Franc',
		currencySymbol: 'FRw',
		countryCode: 'RW',
		countryName: 'Rwanda',
	},
	{
		currencyCode: 'SAR',
		currencyName: 'Saudi Riyal',
		currencySymbol: 'ر.س',
		countryCode: 'SA',
		countryName: 'Saudi Arabia',
	},
	{
		currencyCode: 'SBD',
		currencyName: 'Solomon Islands Dollar',
		currencySymbol: '$',
		countryCode: 'SB',
		countryName: 'Solomon Islands',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'SC',
		countryName: 'Seychelles',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'SD',
		countryName: 'Sudan',
	},
	{
		currencyCode: 'SEK',
		currencyName: 'Swedish Krona',
		currencySymbol: 'kr',
		countryCode: 'SE',
		countryName: 'Sweden',
	},
	{
		currencyCode: 'SGD',
		currencyName: 'Singapore Dollar',
		currencySymbol: '$',
		countryCode: 'SG',
		countryName: 'Singapore',
	},
	{
		currencyCode: 'SHP',
		currencyName: 'Saint Helenian Pound',
		currencySymbol: '£',
		countryCode: 'SH',
		countryName: 'St. Helena',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'SI',
		countryName: 'Slovenia',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'SJ',
		countryName: 'Svalbard & Jan Mayen',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'SK',
		countryName: 'Slovakia',
	},
	{
		currencyCode: 'SLL',
		currencyName: 'Sierra Leonean Leone',
		currencySymbol: 'Le',
		countryCode: 'SL',
		countryName: 'Sierra Leone',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'SM',
		countryName: 'San Marino',
	},
	{
		currencyCode: 'XOF',
		currencyName: 'West African Cfa Franc',
		currencySymbol: 'Fr',
		countryCode: 'SN',
		countryName: 'Senegal',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'SO',
		countryName: 'Somalia',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'SR',
		countryName: 'Suriname',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'SS',
		countryName: 'South Sudan',
	},
	{
		currencyCode: 'STD',
		currencyName: 'São Tomé and Príncipe Dobra',
		currencySymbol: 'Db',
		countryCode: 'ST',
		countryName: 'São Tomé & Príncipe',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'SV',
		countryName: 'El Salvador',
	},
	{
		currencyCode: 'ANG',
		currencyName: 'Netherlands Antillean Gulden',
		currencySymbol: 'ƒ',
		countryCode: 'SX',
		countryName: 'Sint Maarten',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'SZ',
		countryName: 'Eswatini',
	},
	{
		currencyCode: 'GBP',
		currencyName: 'British Pound',
		currencySymbol: '£',
		countryCode: 'TA',
		countryName: 'Tristan da Cunha',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'TC',
		countryName: 'Turks & Caicos Islands',
	},
	{
		currencyCode: 'XAF',
		currencyName: 'Central African Cfa Franc',
		currencySymbol: 'Fr',
		countryCode: 'TD',
		countryName: 'Chad',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'TF',
		countryName: 'French Southern Territories',
	},
	{
		currencyCode: 'XOF',
		currencyName: 'West African Cfa Franc',
		currencySymbol: 'Fr',
		countryCode: 'TG',
		countryName: 'Togo',
	},
	{
		currencyCode: 'THB',
		currencyName: 'Thai Baht',
		currencySymbol: '฿',
		countryCode: 'TH',
		countryName: 'Thailand',
	},
	{
		currencyCode: 'TJS',
		currencyName: 'Tajikistani Somoni',
		currencySymbol: 'ЅМ',
		countryCode: 'TJ',
		countryName: 'Tajikistan',
	},
	{
		currencyCode: 'NZD',
		currencyName: 'New Zealand Dollar',
		currencySymbol: '$',
		countryCode: 'TK',
		countryName: 'Tokelau',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'TL',
		countryName: 'Timor-Leste',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'TM',
		countryName: 'Turkmenistan',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'TN',
		countryName: 'Tunisia',
	},
	{
		currencyCode: 'TOP',
		currencyName: 'Tongan Paʻanga',
		currencySymbol: 'T$',
		countryCode: 'TO',
		countryName: 'Tonga',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'TR',
		countryName: 'Türkiye',
	},
	{
		currencyCode: 'TTD',
		currencyName: 'Trinidad and Tobago Dollar',
		currencySymbol: '$',
		countryCode: 'TT',
		countryName: 'Trinidad & Tobago',
	},
	{
		currencyCode: 'AUD',
		currencyName: 'Australian Dollar',
		currencySymbol: '$',
		countryCode: 'TV',
		countryName: 'Tuvalu',
	},
	{
		currencyCode: 'TWD',
		currencyName: 'New Taiwan Dollar',
		currencySymbol: '$',
		countryCode: 'TW',
		countryName: 'Taiwan',
	},
	{
		currencyCode: 'TZS',
		currencyName: 'Tanzanian Shilling',
		currencySymbol: 'Sh',
		countryCode: 'TZ',
		countryName: 'Tanzania',
	},
	{
		currencyCode: 'UAH',
		currencyName: 'Ukrainian Hryvnia',
		currencySymbol: '₴',
		countryCode: 'UA',
		countryName: 'Ukraine',
	},
	{
		currencyCode: 'UGX',
		currencyName: 'Ugandan Shilling',
		currencySymbol: 'USh',
		countryCode: 'UG',
		countryName: 'Uganda',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'UM',
		countryName: 'U.S. Outlying Islands',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'US',
		countryName: 'United States',
	},
	{
		currencyCode: 'UYU',
		currencyName: 'Uruguayan Peso',
		currencySymbol: '$',
		countryCode: 'UY',
		countryName: 'Uruguay',
	},
	{
		currencyCode: 'UZS',
		currencyName: 'Uzbekistan Som',
		currencySymbol: '',
		countryCode: 'UZ',
		countryName: 'Uzbekistan',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'VA',
		countryName: 'Vatican City',
	},
	{
		currencyCode: 'XCD',
		currencyName: 'East Caribbean Dollar',
		currencySymbol: '$',
		countryCode: 'VC',
		countryName: 'St. Vincent & Grenadines',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'VE',
		countryName: 'Venezuela',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'VG',
		countryName: 'British Virgin Islands',
	},
	{
		currencyCode: 'VND',
		currencyName: 'Vietnamese Đồng',
		currencySymbol: '₫',
		countryCode: 'VN',
		countryName: 'Vietnam',
	},
	{
		currencyCode: 'VUV',
		currencyName: 'Vanuatu Vatu',
		currencySymbol: 'Vt',
		countryCode: 'VU',
		countryName: 'Vanuatu',
	},
	{
		currencyCode: 'XPF',
		currencyName: 'Cfp Franc',
		currencySymbol: 'Fr',
		countryCode: 'WF',
		countryName: 'Wallis & Futuna',
	},
	{
		currencyCode: 'WST',
		currencyName: 'Samoan Tala',
		currencySymbol: 'T',
		countryCode: 'WS',
		countryName: 'Samoa',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'XK',
		countryName: 'Kosovo',
	},
	{
		currencyCode: 'YER',
		currencyName: 'Yemeni Rial',
		currencySymbol: '﷼',
		countryCode: 'YE',
		countryName: 'Yemen',
	},
	{
		currencyCode: 'EUR',
		currencyName: 'Euro',
		currencySymbol: '€',
		countryCode: 'YT',
		countryName: 'Mayotte',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'ZA',
		countryName: 'South Africa',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'ZM',
		countryName: 'Zambia',
	},
	{
		currencyCode: 'USD',
		currencyName: 'United States Dollar',
		currencySymbol: '$',
		countryCode: 'ZW',
		countryName: 'Zimbabwe',
	},
] as const;
export type CountryCode = (typeof countries)[number]['countryCode'];

export const currencies = countries.map(
	({ countryName, currencySymbol, countryCode }) => ({
		id: countryCode,
		name: `${countryName} - ${currencySymbol}`,
	}),
);
